name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.22,<1.24
  - pandas=1.3.3
  - scipy=1.7.3
  - scikit-learn=0.24.2
  - matplotlib=3.4.3
  - seaborn=0.11.2
  - pytest=6.2.4
  - flake8=3.9.2
  - psutil=5.8.0
  - pip
  - pip:
      - py-cpuinfo==9.0.0
      - simpy==4.0.1
