name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - simpy=4.0.1
  - watchdog
  - matplotlib
  - graphviz 
  - pytest    
  - coverage  
  - pip
  - pip:
      - typing
      - graphviz
