name: my_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - simpy
    - pandas
    - numpy
    - paramiko
    - psutil
    - pytest 
    - coverage
    - requests
    - matplotlib
