name: my_env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9  # Set Python version
  - pip         # Include pip for additional package installations
  - pip:
      - psutil       # Library for system and resource monitoring
      - pytest       # Testing framework
      - coverage     # Test coverage tool
