name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - simpy=4.0.1
  - graphviz
  - watchdog
  - os
  - ast
  - matplotlib
  - pip
  - pip:
      - graphviz
      - typing
      - time
      - abc
      - __future__