name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - simpy=4.0.1
  - watchdog
  - matplotlib
  - __future__
  - pip
  - pip:
      - os
      - ast
      - typing
      - time
      - abc