name: Python Package using Conda and Publish Docker Image

on:
  push:
    branches:
      - Kapazitätsprüfung

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.4
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.4'

      - name: Add conda to system path
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: Verify environment.yml exists
        id: check_env
        run: |
          if [ -f ${{ env.BRANCH_NAME }}/environment.yml ]; then echo "found=true" >> $GITHUB_ENV; else echo "found=false" >> $GITHUB_ENV; fi

      - name: Install dependencies
        if: env.found == 'true'
        run: conda env update --file ${{ env.BRANCH_NAME }}/environment.yml --name base

      - name: Lint with flake8
        if: env.found == 'true'
        run: |
          conda install flake8
          conda run -n base flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          conda run -n base flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        if: env.found == 'true'
        run: |
          conda install pytest
          conda run -n base pytest

  build-and-push-docker:
    runs-on: ubuntu-latest

    env:
      BRANCH_NAME: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Verify Dockerfile exists
        id: check_dockerfile
        run: |
          if [ -f ${{ env.BRANCH_NAME }}/Dockerfile ]; then echo "found=true" >> $GITHUB_ENV; else echo "found=false" >> $GITHUB_ENV; fi

      - name: Build and push Docker image
        if: env.found == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./${{ env.BRANCH_NAME }}
          file: ./${{ env.BRANCH_NAME }}/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: tomstaib/sep_dmpg:${{ env.BRANCH_NAME }}
          secrets:
            github_token: ${{ secrets.DOCKER_TOKEN }}

      - name: Logout from Docker Hub
        if: env.found == 'true'
        run: docker logout
